- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/chart-elements/MilestonesArea.ts
> fix: DIPA-167 update milestone's tooltip

- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/chart-elements/MilestonesArea.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/chart.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/chart.component.scss
- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/chart.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/gantt.component.scss
- frontend/projects/dipa-frontend/src/app/modules/overview/overview.component.scss
- DIPA-155: change type of sidenav to over, create toggle function for milestones
- DIPA-160: change project's name color
> fix: DIPA-155, DIPA-160 after code review

- frontend/.eslintrc.js
> DIPA-141: disable-eslint-rule-for-beginning

- server/src/main/resources/db/changelog/db.changelog-v0.5.0-data.yaml
fix: DIPA-163 fix context for new tempaltes
> fix: DIPA-163 fix context for new templates

- frontend/projects/dipa-frontend/src/app/app-routing.module.ts
- frontend/projects/dipa-frontend/src/app/app.component.spec.ts
- frontend/projects/dipa-frontend/src/app/auth.guard.spec.ts
- frontend/projects/dipa-frontend/src/app/authentication.service.spec.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-checklist/single-appointment-form/single-appointment-form.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-data/project-data.component.spec.ts
- frontend/projects/dipa-frontend/src/app/modules/schedules/configuration/configuration.component.html
- frontend/projects/dipa-frontend/src/app/modules/schedules/configuration/configuration.component.spec.ts
- frontend/projects/dipa-frontend/src/app/modules/schedules/configuration/configuration.component.ts
- frontend/projects/dipa-frontend/src/app/modules/schedules/schedules-routing.module.ts
- frontend/projects/dipa-frontend/src/app/modules/schedules/schedules.component.html
- frontend/projects/dipa-frontend/src/app/modules/schedules/schedules.component.scss
- frontend/projects/dipa-frontend/src/app/modules/schedules/schedules.component.spec.ts
- frontend/projects/dipa-frontend/src/app/modules/schedules/schedules.component.ts
- frontend/projects/dipa-frontend/src/app/modules/schedules/schedules.module.ts
- frontend/projects/dipa-frontend/src/app/root/root.component.html
- frontend/projects/dipa-frontend/src/app/root/root.component.spec.ts
fix: use dateChange event instead of change in matDatepicker
> feat: DIPA-274 restrict access for schedules configuration to pmo role

- server/src/main/java/online/dipa/hub/services/TimelineService.java
DIPA-342 update logic for moving the first milestone
> feat: DIPA-342 move first milestone

- frontend/projects/dipa-frontend/src/app/modules/gantt/project-checklist/project-task-form/project-task-form.component.html
- server/src/main/resources/db/changelog/db.changelog-master.yaml
- server/src/main/resources/db/changelog/db.changelog-v0.9.0-data.yaml
fix: DIPA-350 renamed reopen step button text to "Schritt erneut öffnen"
> feat: DIPA-327 changed link url for "IT-Planungsverfahren und ITR4Web"

- frontend/projects/dipa-frontend/src/app/modules/gantt/project-checklist/results-form/results-form.component.ts
- server/src/main/resources/db/changelog/db.changelog-v0.10.0-data.sql
> fix: fix code after testing

- frontend/projects/dipa-frontend/src/app/modules/gantt/project-checklist/results-form/results-form.component.ts
- server/src/main/java/online/dipa/hub/persistence/entities/OptionEntryEntity.java
- server/src/main/java/online/dipa/hub/services/ProjectService.java
- server/src/main/resources/db/changelog/db.changelog-v0.10.0-data.sql
- DIPA-369: fix status options for project tasks
> fix: DIPA-369 fix status project tasks

- frontend/projects/dipa-frontend/src/app/modules/gantt/project-checklist/project-task-form/project-task-form.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-checklist/project-task-form/project-task-form.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-checklist/results-form/results-form.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-checklist/results-form/results-form.component.ts
- frontend/projects/dipa-frontend/src/styles.scss
- server/src/main/resources/db/changelog/db.changelog-v0.10.0-data.sql
and url validation into mat-form-field of type url
fix: adde3d missing TYPE_SUBTASK in showField dropdown
> feat: DIPA-294 added external link icon

- frontend/projects/dipa-frontend/src/app/modules/gantt/project-dialog/project-dialog.component.ts
- server/src/main/java/online/dipa/hub/services/UserInformationService.java
> fix: fix bug create project

- server/src/main/java/online/dipa/hub/server/rest/ProjectController.java
- server/src/main/java/online/dipa/hub/services/UserInformationService.java
> fix: fix DIPA-130

- frontend/projects/dipa-frontend/src/app/modules/gantt/gantt-routing.module.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-checklist/project-checklist.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-checklist/project-checklist.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-checklist/project-task-form/project-task-form.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-checklist/project-task-form/project-task-form.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-control/project-control.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-control/project-control.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-data/project-data.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-quickstart/project-quickstart.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-quickstart/project-quickstart.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/sidenav/sidenav.component.ts
- open-api/src/main/resources/models/projectTask.yml
- server/src/main/java/online/dipa/hub/convert/ProjectTaskEntityToProjectTaskConverter.java
- server/src/main/java/online/dipa/hub/persistence/entities/ProjectTaskEntity.java
- server/src/main/resources/db/changelog/db.changelog-master.yaml
- server/src/main/resources/db/changelog/db.changelog-v0.11.0-data.sql
- server/src/main/resources/db/changelog/db.changelog-v0.12.0-data.sql
- server/src/main/resources/db/changelog/db.changelog-v0.12.0.yaml
feat: DIPA-271 removed "Schritt abschließen" button for permanent tasks
feat: DIPA-271 show icons for permanent tasks instead of numbers
fix: DIPA-345 redirect to project quickstart by default
> fix: DIPA-271 added missing permanent task and changed order

- frontend/projects/dipa-frontend/src/app/app-routing.module.ts
- frontend/projects/dipa-frontend/src/app/auth.guard.ts
- frontend/projects/dipa-frontend/src/app/root/root.component.html
- frontend/projects/dipa-frontend/src/app/root/root.component.ts
- server/src/main/java/online/dipa/hub/services/UserInformationService.java
DIPA-376: user with accesses to project can see project overview
> feature: DIPA-376 project roles project overview

- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/chart.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/chart.component.scss
- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/chart.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/milestone-dialog/milestone-dialog.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/milestone-dialog/milestone-dialog.component.scss
- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/milestone-dialog/milestone-dialog.component.spec.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/milestone-dialog/milestone-dialog.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/gantt.module.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-dialog/project-dialog.component.html
- open-api/src/main/resources/dipa-hub.yaml
- open-api/src/main/resources/paths/deleteMilestone.yml
- open-api/src/main/resources/paths/milestones.yml
- server/src/main/java/online/dipa/hub/persistence/entities/MilestoneTemplateEntity.java
- server/src/main/java/online/dipa/hub/server/rest/MilestoneController.java
- server/src/main/java/online/dipa/hub/services/MilestoneService.java
- DIPA-111, DIPA-110 create and delete milestones
> feat: DIPA-111, DIPA-110 create and delete milestones

- frontend/projects/dipa-frontend/src/app/modules/gantt/project-dialog/project-dialog.component.ts
- DIPA-130 filled operation type, project approach
> fix: DIPA-130 filled operation type, project approach

- frontend/projects/dipa-frontend/src/app/auth.guard.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/milestone-dialog/milestone-dialog.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-dialog/project-dialog.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-dialog/project-dialog.component.ts
- server/src/main/java/online/dipa/hub/services/TimelineService.java
- DIPA-110 fix milestone files
> fix: DIPA-110 fix milestone files

- frontend/projects/dipa-frontend/src/app/modules/gantt/project-data/project-data.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/timeline/schedules/timeline.component.ts
- server/src/main/java/online/dipa/hub/services/MilestoneService.java
- server/src/main/java/online/dipa/hub/services/TimelineService.java
DIPA-111 fix Timeline Enddate, reload project data
> fix: DIPA-111 fix delete all milestones

- server/src/main/resources/db/changelog/db.changelog-master.yaml
- server/src/main/resources/db/changelog/db.changelog-v0.13.0-data.sql
> feat: DIPA-404 test project users

- frontend/projects/dipa-frontend/src/app/authentication.service.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/gantt.module.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-data/project-data.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-dialog/project-dialog.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-role/project-role.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/sidenav/sidenav.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/sidenav/sidenavService.ts
- frontend/projects/dipa-frontend/src/app/shared/timelineDataService.ts
- server/src/main/java/online/dipa/hub/services/TimelineService.java
- DIPA-402 data for project dialog, 
- DIPA-393 update sidenav data
> fix: DIPA-402 data for project dialog, DIPA-393 update sidenav data

- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/chart-elements/MilestonesArea.ts
- server/src/main/resources/db/changelog/db.changelog-v0.13.0-data.sql
DIPA-425, DIPA-422 fix tooltip, checkbox
> fix: DIPA-425, DIPA-422 fix tooltip, checkbox

- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/chart.component.html
- DIPA-399 last milestone delete function
> feature: DIPA-399 last milestone delete function

- frontend/projects/dipa-frontend/src/app/modules/gantt/project-checklist/results-form/results-form.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/timeline/schedules/timeline.component.ts
- server/src/main/resources/db/changelog/db.changelog-master.yaml
- server/src/main/resources/db/changelog/db.changelog-v0.14.0-data.sql
- DIPA-395 change project appointments status
> feat: DIPA-395 project appointments status

- frontend/projects/dipa-frontend/src/app/modules/gantt/timeline/schedules/timeline.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/timeline/schedules/timeline.component.scss
- frontend/projects/dipa-frontend/src/app/modules/gantt/timeline/schedules/timeline.component.ts
* feat: DIPA-390 filter single appointments in a date range or a range preset
* feat: DIPA-390 filter single appointments in a date range or a range preset
* Update timeline.component.html
* feat: DIPA-390 set default appointments list end to project end
> feat: DIPA-390 filter schedule dates (#375)

- frontend/package-lock.json
- frontend/projects/dipa-frontend/src/app/modules/gantt/timeline/schedules/timeline.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/timeline/schedules/timeline.component.scss
- frontend/projects/dipa-frontend/src/app/modules/gantt/timeline/schedules/timeline.component.ts
feat: DIPA-417 added appointment type for TYPE_SINGLE_APPOINTMENT and TYPE_APPT_SERIES
> fix: DIPA-390 refresh appointments list at first load

- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/milestone-dialog/milestone-dialog.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/milestone-dialog/milestone-dialog.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/gantt.module.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-dialog/project-dialog.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-dialog/project-dialog.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/timeline/schedules/timeline.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/timeline/schedules/timeline.component.ts
DIPA-428 change datepicker to date input
> fix: DIPA-428 change datepicker to date input

- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/milestone-dialog/milestone-dialog.component.ts
> fix: DIPA-428-fix-snackbar

- frontend/projects/dipa-frontend/src/app/menus/gantt-menu/gantt-menu.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/chart-header/chart-header.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/chart-header/chart-header.component.scss
- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/chart-header/chart-header.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/chart.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/chart.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-checklist/project-task-form/project-task-form.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-checklist/project-task-form/project-task-form.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-checklist/results-form/results-form.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-checklist/results-form/results-form.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-control/project-control.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-data/project-data.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-organization/project-organization.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-organization/project-organization.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-quickstart/project-quickstart.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-role/project-role.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-role/project-role.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-settings-dialog/project-settings-dialog.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/sidenav/sidenav.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/timeline/schedules/timeline.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/timeline/templates-view/templates-view.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/timeline/templates-view/templates/templates.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/timeline/templates-view/templates/templates.component.ts
- server/src/main/java/online/dipa/hub/services/TimelineService.java
feat: DIPA-449 disable all edit fields for archived projects in frontend
> feat: DIPA-449 link button from project overview / archive to project details

- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/chart-elements/EventsArea.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/chart.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-checklist/project-task-form/project-task-form.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/timeline/schedules/timeline.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/timeline/schedules/timeline.component.ts
- server/src/main/resources/db/changelog/db.changelog-master.yaml
- server/src/main/resources/db/changelog/db.changelog-v0.14.0-data-2.sql
feat: DIPA-414 added buttons to hide/show all overdue/upcoming events in the chart
fix: generate all initial event entries in db for example projects
> fix: DIPA-414 redraw event items in chart after milestones have changed

- frontend/projects/dipa-frontend/src/app/modules/gantt/chart/chart-header/chart-header.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/gantt-routing.module.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/gantt.module.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-dashboard/project-dashboard.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-dashboard/project-dashboard.component.scss
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-dashboard/project-dashboard.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/sidenav/sidenav.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/timeline/schedules/timeline.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/timeline/schedules/timeline.component.scss
- frontend/projects/dipa-frontend/src/app/shared/utils.ts
- open-api/src/main/resources/models/externalLink.yml
- server/README.md
- server/src/main/resources/db/changelog/db.changelog-v0.17.0-data.sql
feat: introduced different colors for event types
> feat: DIPA-450 added project overview dashboard

- frontend/projects/dipa-frontend/src/app/shared/external-link/external-link.component.html
- frontend/projects/dipa-frontend/src/app/shared/external-link/external-link.component.ts
- frontend/projects/dipa-frontend/src/app/shared/invalid-link-check.directive.ts
- frontend/projects/dipa-frontend/src/app/shared/invalid-link-dialog/invalid-link-dialog.component.html
- frontend/projects/dipa-frontend/src/app/shared/nav-menu-list-item/nav-menu-list-item.component.html
- frontend/projects/dipa-frontend/src/app/shared/nav-menu-list-item/nav-menu-list-item.component.ts
- frontend/projects/dipa-frontend/src/app/shared/shared.module.ts
moved link validity check into invalid-link-check directive
> feat: DIPA-499 add invalid link dialog for favorite links

- frontend/projects/dipa-frontend/src/app/modules/gantt/gantt.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/gantt.component.scss
- frontend/projects/dipa-frontend/src/app/modules/gantt/gantt.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-dashboard/project-dashboard.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-dashboard/project-dashboard.component.scss
- frontend/projects/dipa-frontend/src/app/modules/gantt/sidenav/sidenav.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/sidenav/sidenav.component.scss
- frontend/projects/dipa-frontend/src/app/modules/gantt/sidenav/sidenav.component.ts
- frontend/projects/dipa-frontend/src/styles.scss
feat: made side menu toggleable
> feat: DIPA-502 show important project information at the top of side menu

- server/src/main/resources/db/changelog/db.changelog-master.yaml
- server/src/main/resources/db/changelog/db.changelog-v0.20.0-data.sql
- server/src/main/resources/db/changelog/db.changelog-v0.20.0-reset-sequences.sql
BA Lifecycle milestone template
> feat: DIPA-515 added BA Lifecycle project approach

- frontend/projects/dipa-frontend/src/app/modules/configuration/plan-template-dialog/plan-template-dialog.component.ts
- frontend/projects/dipa-frontend/src/app/modules/configuration/plan-template-form/plan-template-form.component.html
- frontend/projects/dipa-frontend/src/app/modules/configuration/plan-template-form/plan-template-form.component.ts
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-dialog/project-dialog.component.html
- frontend/projects/dipa-frontend/src/app/modules/gantt/project-dialog/project-dialog.component.ts
- server/src/main/resources/db/changelog/db.changelog-v0.20.0-data.sql
optimized form validation to show error messages on submit
reset project approach after operation type changed in project-dialog
> removed preselected project approach when creating new plan template
